# Generated by Django 4.1.3 on 2022-11-20 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_alter_enrollment_enrolled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classhistory',
            old_name='_coach',
            new_name='Coach',
        ),
        migrations.RenameField(
            model_name='classhistory',
            old_name='end_Recursion',
            new_name='End_Recursion',
        ),
        migrations.RenameField(
            model_name='classhistory',
            old_name='end_Time',
            new_name='End_Time',
        ),
        migrations.RenameField(
            model_name='classhistory',
            old_name='enrollment_status',
            new_name='Enrollment_Status',
        ),
        migrations.RenameField(
            model_name='classhistory',
            old_name='_keywords',
            new_name='Keywords',
        ),
        migrations.RenameField(
            model_name='classhistory',
            old_name='_name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='classhistory',
            old_name='start_Recursion',
            new_name='Start_Recursion',
        ),
        migrations.RenameField(
            model_name='classhistory',
            old_name='start_Time',
            new_name='Start_Time',
        ),
        migrations.RenameField(
            model_name='classhistory',
            old_name='_studio',
            new_name='Studio',
        ),
        migrations.RenameField(
            model_name='classhistory',
            old_name='_user',
            new_name='User',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='enroll_or_drop',
            new_name='_enroll_or_drop',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='enrolled',
            new_name='_enrolled',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='user',
            new_name='_user',
        ),
    ]
