# Generated by Django 4.1.3 on 2022-12-10 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_type', models.CharField(choices=[['150', 'Annual Plan'], ['15', 'Monthly Plan'], ['200', 'Premium Annual Plan']], default=None, max_length=50)),
                ('duration', models.PositiveIntegerField(default=30)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserMemberships',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_info', models.CharField(max_length=120)),
                ('isActiveMembership', models.BooleanField(default=True)),
                ('next_payment', models.DateField(blank=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userMembership', to='subscriptions.plans')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userMembership', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPayHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='None', max_length=120)),
                ('Membership', models.CharField(blank=True, max_length=120, null=True)),
                ('Card_info', models.CharField(max_length=120)),
                ('IsActiveMembership', models.BooleanField(default=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('Next_payment', models.DateField(blank=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.usermemberships')),
            ],
        ),
    ]
