# Generated by Django 4.1.3 on 2022-12-02 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_rename__coach_classhistory_coach_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
