# Generated by Django 4.1.3 on 2022-12-03 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_class_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='is_active',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='_is_active',
            field=models.BooleanField(default=True),
        ),
    ]
